package myapps.solutions.wrapper.model;
// Generated Apr 20, 2017 3:00:30 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AccountDevice generated by hbm2java
 */
@Entity
@Table(name = "account_device", catalog = "wrapper")
public class AccountDevice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1811046620215867785L;
	private Integer id;
	private UserDetails userDetails;
	private String deviceName;
	private String deviceType;
	private String macAddress;

	public AccountDevice() {
	}

	public AccountDevice(UserDetails userDetails, String deviceName, String deviceType, String macAddress) {
		this.userDetails = userDetails;
		this.deviceName = deviceName;
		this.deviceType = deviceType;
		this.macAddress = macAddress;
	}

	public AccountDevice(String deviceName, String deviceType, String macAddress) {
		this.deviceName = deviceName;
		this.deviceType = deviceType;
		this.macAddress = macAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@JsonIgnore
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	@JsonIgnore
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "deviceName", nullable = false, length = 45)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Column(name = "deviceType", nullable = false, length = 45)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "macAddress", nullable = false, length = 45)
	public String getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

}
