package myapps.solutions.wrapper.model;
// Generated Sep 6, 2017 6:35:20 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OauthClientDetails generated by hbm2java
 */
@Entity
@Table(name = "oauth_client_details", catalog = "wrapper")
public class OauthClientDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3573994926192670361L;
	private String clientId;
	private UserDetails userDetails;
	private String resourceIds;
	private String clientSecret;
	private String scope;
	private String authorizedGrantTypes;
	private Integer accessTokenValidity;
	private Integer refreshTokenValidity;

	public OauthClientDetails() {
	}

	public OauthClientDetails(String clientId, UserDetails userDetails, String clientSecret) {
		this.clientId = clientId;
		this.userDetails = userDetails;
		this.clientSecret = clientSecret;
	}
	
	public OauthClientDetails(UserDetails userDetails, String clientId, String clientSecret) {
		this.clientId = clientId;
		this.userDetails = userDetails;
		this.clientSecret = clientSecret;
	}

	public OauthClientDetails(String clientId, UserDetails userDetails, String resourceIds, String clientSecret,
			String scope, String authorizedGrantTypes, Integer accessTokenValidity, Integer refreshTokenValidity) {
		this.clientId = clientId;
		this.userDetails = userDetails;
		this.resourceIds = resourceIds;
		this.clientSecret = clientSecret;
		this.scope = scope;
		this.authorizedGrantTypes = authorizedGrantTypes;
		this.accessTokenValidity = accessTokenValidity;
		this.refreshTokenValidity = refreshTokenValidity;
	}

	@Id

	@Column(name = "client_id", unique = true, nullable = false, length = 256)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "resource_ids", length = 256, nullable = false, insertable = false)
	public String getResourceIds() {
		return this.resourceIds;
	}

	public void setResourceIds(String resourceIds) {
		this.resourceIds = resourceIds;
	}

	@Column(name = "client_secret", nullable = false, length = 256)
	public String getClientSecret() {
		return this.clientSecret;
	}

	public void setClientSecret(String clientSecret) {
		this.clientSecret = clientSecret;
	}

	@Column(name = "scope", length = 256, nullable = false, insertable = false)
	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	@Column(name = "authorized_grant_types", length = 256, nullable = false, insertable = false)
	public String getAuthorizedGrantTypes() {
		return this.authorizedGrantTypes;
	}

	public void setAuthorizedGrantTypes(String authorizedGrantTypes) {
		this.authorizedGrantTypes = authorizedGrantTypes;
	}

	@Column(name = "access_token_validity", nullable = false, insertable = false)
	public Integer getAccessTokenValidity() {
		return this.accessTokenValidity;
	}

	public void setAccessTokenValidity(Integer accessTokenValidity) {
		this.accessTokenValidity = accessTokenValidity;
	}

	@Column(name = "refresh_token_validity", nullable = false, insertable = false)
	public Integer getRefreshTokenValidity() {
		return this.refreshTokenValidity;
	}

	public void setRefreshTokenValidity(Integer refreshTokenValidity) {
		this.refreshTokenValidity = refreshTokenValidity;
	}

}
