package myapps.solutions.wrapper.model;
// Generated May 8, 2017 3:02:42 PM by Hibernate Tools 5.2.1.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "package", catalog = "wrapper")
public class Package implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1003817215981864441L;
	private int id;
	private Product product;
	private String name;
	private String licenseType;
	private String description;
	private byte[] icon;
	private List<Subscription> subscriptions = new ArrayList<Subscription>(0);
	private List<UserSubscription> userSubscriptions = new ArrayList<UserSubscription>(0);

	public Package() {
	}

	public Package(int id) {
		this.id = id;
	}

	public Package(int id, Product product, String name, String licenseType, String description, byte[] icon,
			List<Subscription> subscriptions, List<UserSubscription> userSubscriptions) {
		this.id = id;
		this.product = product;
		this.name = name;
		this.licenseType = licenseType;
		this.description = description;
		this.icon = icon;
		this.subscriptions = subscriptions;
		this.userSubscriptions = userSubscriptions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnore
	@JoinColumn(name = "productId")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "licenseType", length = 45)
	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "icon")
	public byte[] getIcon() {
		return this.icon;
	}

	public void setIcon(byte[] icon) {
		this.icon = icon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "package")
	public List<Subscription> getSubscriptions() {
		return this.subscriptions;
	}

	public void setSubscriptions(List<Subscription> subscriptions) {
		this.subscriptions = subscriptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "package")
	public List<UserSubscription> getUserSubscriptions() {
		return this.userSubscriptions;
	}

	public void setUserSubscriptions(List<UserSubscription> userSubscriptions) {
		this.userSubscriptions = userSubscriptions;
	}

}
