package myapps.solutions.wrapper.model;
// Generated Apr 20, 2017 3:00:30 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", catalog = "wrapper")
public class Photo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6849695797506439984L;
	private int userId;
	private UserDetails userDetails;
	private byte[] image;

	public Photo() {
	}

	public Photo(UserDetails userDetails, byte[] image) {
		this.userDetails = userDetails;
		this.image = image;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userDetails"))
	@Id
	@GeneratedValue(generator = "generator")
	@JsonIgnore
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@JsonIgnore
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
