package myapps.solutions.wrapper.model;
// Generated Aug 12, 2017 4:33:07 PM by Hibernate Tools 5.2.1.Final
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TermsConditionsHistory generated by hbm2java
 */
@Entity
@Table(name = "terms_conditions_history", catalog = "wrapper")
public class TermsConditionsHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6813265248821491039L;
	private Integer id;
	private TermsConditions termsConditions;
	private UserDetails userDetails;
	private Date date;

	public TermsConditionsHistory() {
	}

	public TermsConditionsHistory(TermsConditions termsConditions, UserDetails userDetails, Date date) {
		this.termsConditions = termsConditions;
		this.userDetails = userDetails;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@JsonIgnore
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "terms_conditions_id", nullable = false)
	public TermsConditions getTermsConditions() {
		return this.termsConditions;
	}

	public void setTermsConditions(TermsConditions termsConditions) {
		this.termsConditions = termsConditions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	@JsonIgnore
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
