package myapps.solutions.wrapper.model;
// Generated Feb 13, 2018 3:00:19 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tokens generated by hbm2java
 */
@Entity
@Table(name = "tokens", catalog = "wrapper")
public class Tokens implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8977805294479527348L;
	private int userId;
	private UserDetails userDetails;
	private String token;
	private String otp;

	public Tokens() {
	}

	public Tokens(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Tokens(UserDetails userDetails, String token, String otp) {
		this.userDetails = userDetails;
		this.token = token;
		this.otp = otp;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userDetails"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@JsonIgnore
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "token", length = 45)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "otp", length = 6)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

}
