package myapps.solutions.wrapper.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserPref generated by hbm2java
 */
@Entity
@Table(name = "user_pref", catalog = "huddil", uniqueConstraints = { @UniqueConstraint(columnNames = "sessionId"),
		@UniqueConstraint(columnNames = "userType") })
public class UserPref implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5281772007399064440L;
	private int userId;
	private String city;
	private Integer userType;
	private String sessionId;
	private String emailId;
	private String mobileNo;
	private String displayName;
	
	public UserPref() {
	}

	public UserPref(int userId, int userType, String emailId, String mobileNo, String displayName) {
		this.userId = userId;
		this.userType = userType;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.displayName = displayName;
	}

	public UserPref(int userId, String sessionId, double percentage, String emailId, String mobileNo, String displayName) {
		this.userId = userId;
		this.sessionId = sessionId;
		this.emailId = emailId;
		this.mobileNo = mobileNo;
		this.displayName = displayName;
	}

	public UserPref(int userId, int userType, double percentage, String emailId, String displayName) {
		this.userId = userId;
		this.userType = userType;
		this.emailId = emailId;
		this.displayName = displayName;
	}

	@Id

	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	/*
	 * @ManyToOne(fetch = FetchType.LAZY)
	 * 
	 * @JoinColumn(name = "lastCity")
	 */
	@Column(name = "lastCity", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	/*
	 * @ManyToOne(fetch = FetchType.LAZY)
	 * 
	 * @JoinColumn(name = "userType", unique = true)
	 */
	@Column(name = "userType", nullable = false)
	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	@Column(name = "sessionId", unique = true, nullable = false, length = 128)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "emailId", nullable = false, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}
	
	@Column(name = "mobileNo", nullable = false, length = 45)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "displayName", nullable = false, length = 45)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
}
