package myapps.solutions.wrapper.model;
// Generated May 5, 2017 4:29:55 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "user_session", catalog = "wrapper")
public class UserSession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8376965748862799908L;
	private int sNo;
	private String macAddress;
	private int userId;
	private Date loggedIn;
	private Boolean isActive;
	private String sessionId;

	public UserSession() {
	}

	public UserSession(String macAddress, int userId) {
		this.macAddress = macAddress;
		this.userId = userId;
	}

	public UserSession(String macAddress, int userId, Date loggedIn, Boolean isActive, String sessionId) {
		this.macAddress = macAddress;
		this.userId = userId;
		this.loggedIn = loggedIn;
		this.isActive = isActive;
		this.sessionId = sessionId;
	}

	@Id
	@Column(name = "sNo", unique = true, nullable = false)
	public int getsNo() {
		return sNo;
	}

	public void setsNo(int sNo) {
		this.sNo = sNo;
	}

	@Column(name = "macAddress")
	public String getMacAddress() {
		return macAddress;
	}

	public void setMacAddress(String macAddress) {
		this.macAddress = macAddress;
	}

	@Column(name = "userId")
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "loggedIn", length = 19)
	public Date getLoggedIn() {
		return this.loggedIn;
	}

	public void setLoggedIn(Date loggedIn) {
		this.loggedIn = loggedIn;
	}

	@Column(name = "isActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "sessionId", length = 128)
	public String getSessionId() {
		return sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

}
