package myapps.solutions.wrapper.model;
// Generated Apr 20, 2017 2:57:48 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Wallet generated by hbm2java
 */
@Entity
@Table(name = "wallet", catalog = "wrapper")
public class Wallet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6541753948715526850L;
	private int userId;
	private UserDetails userDetails;
	private int points;

	public Wallet() {
	}

	public Wallet(UserDetails userDetails, int points) {
		this.userDetails = userDetails;
		this.points = points;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userDetails"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "userId", unique = true, nullable = false)
	@JsonIgnore
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	@JsonIgnore
	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	@Column(name = "points", nullable = false)
	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

}
